version: "3.8"

services:
  app:
    image: mimidots/php7.4:1.0.0-alpine
    volumes:
      - $PWD:/var/www/html
    restart: on-failure
    ports:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - esoko

networks:
  esoko:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.24/29
