version: "3.8"

services:
  app:
    image: ${PHP_IMAGE:-mimidots/php7.4:1.0.4}
    volumes:
      - $PWD:/var/www/html
      - ${HOST_STORAGE_PATH:-./storage}:/var/www/html/storage
    restart: on-failure
    ports:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - esoko

networks:
  esoko:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.24/29
