---
name: Release
on:
  workflow_run:
    workflows: [ 'ci' ]
    types: [ 'completed' ]
    branches: [ 'master' ]

jobs:
  checkout:
    if: github.event.workflow_run.conclusion == 'success'
    name: Checkout and release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create folder to hold configuration
        run: sudo mkdir -p /home/ansible-temp

      - name: Run ansible deployment playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{github.workspace}}/.ansible/playbooks/release.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.ANSIBLE_VAULT_PASSWORD}}
          requirements: ${{github.workspace}}/.ansible/files/requirements.yml
          directory: /home/ansible-temp
          inventory: |
            [all]
            ${{secrets.MAIN_SERVER}}
          options: |
            -u  ${{secrets.SSH_USER}}
            -e  "local_path=${{github.workspace}}"
            -e  "remote_path=${{secrets.REMOTE_WORKSPACE}}"
            -e  "remote_files_owner_user=${{secrets.REMOTE_FILES_OWNER}}"
            -e  "remote_files_owner_group=${{secrets.REMOTE_FILES_GROUP}}"
